<h2>Current Entries</h2>
<table>
	<tr>
		<th>Title</th>
		<th>Date</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	
	<?php foreach($this->articles as $article): ?>
		<tr>
			<td>
				<a href='articles/<?=$article->getUrl(); ?>'>
					<?=$article->getTitle(); ?>
				</a>
			</td>

			<td>
				<?=$article->getNicePubDate(); ?>
			</td>

			<td>
				<a href='#' onclick='editBlogEntry(<?=$article->getId(); ?>)'>
					<i class="fa fa-pencil-square-o"></i>
				</a>
			</td>

			<td>
				<a href='#' onclick='deleteBlogEntry(<?=$article->getId(); ?>)'>
					<i class="fa fa-times fa-lg"></i>
				</a>
			</td>
		</tr>
	<?php endforeach; ?>

</table>