<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="http://localhost:8080/a-food-odyssey/" />
        <title>
            <?php echo $this->article->getTitle(); ?> - Blog Standard Food
        </title>
        <link rel="stylesheet" href="css/reset.css">
        <link rel="stylesheet" href="css/article-style.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,800' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

        <link href='//cdn.knightlab.com/libs/soundcite/latest/css/player.css' rel='stylesheet' type='text/css'>
        
    </head>

    <body>

        <div class="grid-container">
            <header id="site-header">
                <a href="index.php" class="no-decoration">
                    <img src="assets/bsf-logo-dark.png" alt="blog standard food logo" />
                </a>
                <nav>
                    <ul>
                        <li><a href="index.php"><span>THE</span> Archives</a></li>
                        <li><a href="the-lexicon.html"><span>THE</span> Lexicon</a></li>
                        <li><a href="the-soundtrack.html"><span>THE</span> Soundtrack</a></li>
                        <li><a href="#"><span>THE</span> Lowdown</a></li>
                    </ul>
                </nav>
            </header>
        </div>


        <header id="article-header" 
                style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.6)), 
                    url('img/<?php echo $this->article->getBannerImagePath(); ?>')">
            <div class="article-header-container">
                <h1>
                    <?php echo $this->article->getTitle(); ?>
                </h1>
                <p>
                    <abbr title="too long, didn't read. A quick summary for those who are in a rush">
                        tldr&#59; 
                    </abbr>
                    <?php echo $this->article->getSummary(); ?>
                </p>
            </div>
        </header>


        <div class="grid-container">
            <aside id="article-info">

                <ul>
                    <li id="article-number"> No: 
                        <span id="article-num">
                            <?php echo $this->article->getId(); ?>
                        </span>
                        <a href="articles/<?php echo $this->article->getPreviousArticleUrl(); ?>">&larr;</a> 
                        <a href="articles/<?php echo $this->article->getNextArticleUrl(); ?>">&rarr;</a>
                    </li>

                    <li id="article-date">
                        <time datetime="<?php echo $this->article->getHtmlPubDate(); ?>"> 
                            <?php echo $this->article->getNicePubDate(); ?>
                        </time>
                    </li>

                    <li id="article-tags">

                        <?php
                            $tags = $this->article->getTagsAsArray();
                            $tagCount = count($tags);

                            for($i = 0; $i < $tagCount; $i++)
                            {
                                echo "<a href='tags/" . $tags[$i] . "'> " . $tags[$i] . "</a>";

                                if ($i != $tagCount - 1)
                                {
                                    echo " //";
                                }
                            }
                        ?>

                    </li>
                </ul>

                <h4>What to do</h4>
                <?php echo $this->article->getDirectionsHtml(); ?>
            </aside>

            <article id="main-article">
                <?php echo $this->article->getContentHtml(); ?>

                <div id="comments-toggle">
                    <h3 id="comments-toggle-text">
                        <?php
                            $nComments = count($this->article->getComments()); 

                            if ($nComments === 0)
                            {
                                echo "No comments yet, be the first?";
                            }
                            else if ($nComments === 1)
                            {
                                echo "1 comment";
                            }
                            else
                            {
                                echo $nComments . " comments";
                            }
                        ?>
                    </h3>
                </div>

                <div id="comments" class="comments-shrunk">
                    <?php foreach($this->article->getComments() as $comment): ?>
                        <article class="comment">
                            <img src="http://www.gravatar.com/avatar/<?=$comment->getGravatarHash(); ?>?d=monsterid" alt="gravatar" />
                            <div class="comment-container">
                                <h5>
                                    <?=htmlspecialchars($comment->getName()); ?>
                                </h5>
                                <p class="comment-meta">
                                    <time datetime="<?=$comment->getHtmlDate(); ?>">
                                        <?=$comment->getNiceDate(); ?>
                                    </time>
                                </p>
                                <p class="comment-text">
                                    <?=htmlspecialchars($comment->getComment()); ?>
                                </p>
                            </div>
                        </article>
                    <?php endforeach; ?>
                </div>

            </article>

            <aside id="article-share">
                <h4>Share this article</h4>
                <ul>
                    <li id="share-twitter"><a href="https://twitter.com/share?hashtags=Blog%Standard%20Food" class="no-decoration" target="_blank"><i class="fa fa-twitter fa-2x"></i></a></li>
                    <li id="share-facebook"><a href="#" class="no-decoration" id="fb-link" target="_blank"><i class="fa fa-facebook fa-2x"></i></a></li>
                    <li id="share-google"><a href="#" class="no-decoration" id="google-link" target="_blank"><i class="fa fa-google-plus fa-2x"></i></a></li>
                </ul>

                <h5>Get involved</h5>
                <form method="POST">
                    <input type="text" id="author" name="author" placeholder="your name" maxlength="20" required />
                    <input type="email" id="email" name="email" placeholder="your email *" maxlength="50" />
                    <textarea id="comment" name="comment" placeholder="comment..." rows="5" required></textarea>
                    <button type="submit" id="post-comment-btn">Post</button>
                </form>
                <small>* Optional for <a href="https://en.gravatar.com/">gravatars</a>. We will never store or display it</small>
                <p id="comment-result"></p>
            </aside>

        </div>
            

        <footer>
            <p>Blog Standard Food is <a href="http://www.pjfreeman.co.uk/">Phil Freeman</a> &amp; 
                <a href="http://poc275.co.uk">Peter O'Connor</a>
            </p>

            <address id="footer-social">
                <ul id="footer-logos">
                    <li><a href="mailto:poc275@gmail.com?Subject=Blog%20Standard%20Food" title="send us an email" class="no-decoration"><i class="fa fa-envelope-o fa-4x"></i></a></li>
                    <li><a href="rss.xml" title="follow our blog" class="no-decoration"><i class="fa fa-rss fa-4x"></i></a></li>
                </ul>
            </address>

            <small>
                <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
                <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
                </a>
                <br />
                <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Blog Standard Food</span> is licensed under a 
                <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a> 2016.
            </small>
        </footer>


        <script type="text/javascript" src="js/UpdateShareLinks.js"></script>
        <script type="text/javascript" src="js/AddComment.js"></script>
        <script type="text/javascript" src="js/ShowComments.js"></script>

        <script type='text/javascript' src='//cdn.knightlab.com/libs/soundcite/latest/js/soundcite.min.js'></script>
    </body>

</html>