<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>
            <?php echo $this->article->getTitle(); ?> - A Food Odyssey
        </title>
        <link rel="stylesheet" href="../css/reset.css">
        <link rel="stylesheet" href="../css/article-style.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,800' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400italic,400' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    </head>

    <body>

        <div class="grid-container">
            <header id="site-header">
                <h1>A Food <i>Odyssey</i></h1>
                <p id="tagline">Amateurs trawl through the world of food...</p>
                <nav>
                    <ul>
                        <li><a href="#">THE Archives</a></li>
                        <li><a href="#">THE Lexicon</a></li>
                        <li><a href="#">ABOUT Us</a></li>
                    </ul>
                </nav>
            </header>
        </div>


        <header id="article-header" 
                style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.2), rgba(0, 0, 0, 0.6)), 
                    url('../img/<?php echo $this->article->getBannerImagePath(); ?>')">
            <div class="article-header-container">
                <h1>
                    <?php echo $this->article->getTitle(); ?>
                </h1>
                <p>
                    <abbr title="too long, didn't read. A quick summary for those who are in a rush">
                        tldr&#59; 
                    </abbr>
                    <?php echo $this->article->getSummary(); ?>
                </p>
            </div>
        </header>


        <div class="grid-container">
            <aside id="article-info">
                <p>
                    <!-- TO DO - links to next and previous articles -->
                    No: 
                    <span id="article-num">
                        <?php echo $this->article->getId(); ?>
                    </span>
                    <a href="#">&larr;</a> <a href="#">&rarr;</a>
                </p>
                <p>
                    <i class="fa fa-calendar"></i> 
                    <time datetime="<?php echo $this->article->getHtmlPubDate(); ?>"> 
                        <?php echo $this->article->getNicePubDate(); ?>
                    </time>
                </p>
                <p>
                    <i class="fa fa-tags"></i> 
                    <?php echo $this->article->getTags(); ?>
                </p>

                <!-- TO DO - add a method to the Article class -->
                <h4>What to do:</h4>
                <?php echo $this->article->getDirectionsHtml(); ?>
            </aside>

            <article id="main-article">
                <?php echo $this->article->getContentHtml(); ?>

                <div id="comments-toggle"><h3 id="comments-toggle-text">Comments</h3></div>

                <div id="comments" class="comments-shrunk">
                    <?php foreach($this->article->getComments() as $comment): ?>
                        <article class="comment">
                            <h5>
                                <?=htmlspecialchars($comment->getName()); ?>
                            </h5>
                            <p>
                                <time datetime="<?=$comment->getHtmlDate(); ?>">
                                    <?=$comment->getNiceDate(); ?>
                                </time>
                            </p>
                            <p>
                                <?=htmlspecialchars($comment->getComment()); ?>
                            </p>
                        </article>
                    <?php endforeach; ?>
                </div>

            </article>

            <aside id="article-share">
                <h4>Share this article</h4>
                <ul>
                    <li id="share-twitter"><a href="#" class="no-decoration"><i class="fa fa-twitter fa-2x"></i></a></li>
                    <li id="share-facebook"><a href="#" class="no-decoration"><i class="fa fa-facebook fa-2x"></i></a></li>
                    <li id="share-google"><a href="#" class="no-decoration"><i class="fa fa-google-plus fa-2x"></i></a></li>
                </ul>

                <h5>Get involved</h5>
                <form action="addBlogComment.php" method="POST">
                    <input type="text" id="author" name="author" placeholder="your name" maxlength="50" required />
                    <textarea id="comment" name="comment" placeholder="comment" rows="5" required></textarea>
                    <button type="submit" id="post-comment-btn">Post</button>
                </form>
            </aside>

        </div>
            

        <footer>
            <p>A Food Odyssey is a journey by <a href="http://www.pjfreeman.co.uk/">Phil Freeman</a> &amp; 
                <a href="http://poc275.co.uk">Peter O'Connor</a>
            </p>
            <address id="footer-social">
                <ul id="footer-logos">
                    <li><a href="#" title="send us an email" class="no-decoration"><i class="fa fa-envelope-o fa-4x"></i></a></li>
                    <li><a href="../rss.xml" title="follow our blog" class="no-decoration"><i class="fa fa-rss fa-4x"></i></a></li>
                </ul>
            </address>
        </footer>


        <script type="text/javascript" src="../js/AddComment.js"></script>
        <script type="text/javascript" src="../js/ShowComments.js"></script>
    </body>

</html>