<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->article->getTitle() ?> - The Ponderers Cookbook</title>
        <link rel="stylesheet" href="../css/reset.css">
        <link rel="stylesheet" href="../css/article-style.css">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    </head>

    <body>
        <div id="page">
            <div id="inner">
                <header>
                    <h1>The Ponderers Cookbook</h1>
                    <h2><span>Musings from a couple of amateur cooks</span></h2>
                    <nav>
                        <ul>
                            <li>
                                <a href="#"><i>Visit</i>The Archives</a>
                            </li>
                            <li>
                                <a href="#"><i>The</i>Lexicon</a>
                            </li>
                            <li>
                                <a href="#"><i>About</i>Our Blog</a>
                            </li>
                        </ul>
                    </nav>
                </header>

                <article>
                    <?php
                        echo '<h3>' . $this->article->getTitle() . '</h3>';
                        echo '<h4>tldr&#59; ' . $this->article->getSummary() . '</h4>';
                    ?>

                    <div id="share-links">
                        <i class="fa fa-archive"> No:
                            <span id="article-num">
                                <?php echo $this->article->getId(); ?>
                            </span>
                        </i>
                        <i class="fa fa-calendar-o">
                            <time datetime="<?php echo $this->article->getHtmlPubDate(); ?>">
                                <?php echo $this->article->getNicePubDate(); ?>
                            </time>
                        </i>
                        <i class="fa fa-tags">
                            <?php echo $this->article->getTags(); ?>
                        </i>
                        <i><a href="https://twitter.com/share" class="twitter-share-button" data-via="poc275" 
                            data-hashtags="pondererscookbook">Tweet</a></i>
                        <i class="g-plus" data-action="share" data-annotation="bubble"></i>
                        <div class="fb-share-button" data-layout="button_count"></div>
                    </div>

                    <?php echo $this->article->getContentHtml(); ?>

                </article>


                <div id="comments-toggle">Other Ponderings</div>
                
                <div id="comments" class="comments-shrunk">

                    <?php foreach($this->article->getComments() as $comment): ?>
                        <article class="comment">
                            <p><?=htmlspecialchars($comment->getName()); ?>, 
                                <?=$comment->getNiceDate(); ?></p>
                            <p><?=htmlspecialchars($comment->getComment()); ?></p>
                        </article>
                    <?php endforeach; ?>

                    <div id="comments-form">
                        <h3>Join the discussion</h3>
                        <form action="addBlogComment.php" method="POST">
                            <input type="text" id="author" name="author" placeholder="your name" maxlength="50" required />
                            <textarea id="comment" name="comment" rows="3" required>comment...</textarea>
                            <button type="submit" id="post-comment-btn">Post</button>
                        </form>
                    </div>
                <div>


                <footer>
                    <p>The ponderers are <a href="http://www.pjfreeman.co.uk/">Phillip Freeman</a> &amp; 
                        <a href="http://poc275.co.uk">Peter O'Connor</a></p>
                    <p>Illustrations by <a href="http://en.wikipedia.org/wiki/Sidney_Paget">Sidney Paget</a></p>

                    <address id="footer-social">
                        <ul id="footer-logos">
                            <li>
                                <a href="#" title="send us an email"><i class="fa fa-envelope-o fa-4x"></i></a>
                            </li>
                            <li>
                                <a href="#" title="find us on facebook"><i class="fa fa-facebook-square fa-4x"></i></a>
                            </li>
                            <li>
                                <a href="#" title="tweet us"><i class="fa fa-twitter fa-4x"></i></a>
                            </li>
                            <li>
                                <a href="../rss.xml" title="follow our blog"><i class="fa fa-rss fa-4x"></i></a>
                            </li>
                        </ul>
                    </address>
                </footer>

            </div>
        </div>
        
        <div id="fb-root"></div>
        <script>(function(d, s, id) {
              var js, fjs = d.getElementsByTagName(s)[0];
              if (d.getElementById(id)) return;
              js = d.createElement(s); js.id = id;
              js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.0";
              fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
        <script src="https://apis.google.com/js/platform.js" async defer></script>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
        </script>
        <script type="text/javascript" src="../js/AddComment.js"></script>
        <script type="text/javascript" src="../js/ShowComments.js"></script>

    </body>
</html>