<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <base href="http://localhost:8080/a-food-odyssey/" />
        <title>Blog Standard Food</title>
        <link rel="stylesheet" href="css/reset.css">
        <link rel="stylesheet" href="css/article-style.css">
        <link rel="stylesheet" href="css/home-page-style.css">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300,600,800' rel='stylesheet' type='text/css'>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    </head>

    <body>

        <header id="home-page-header">
            <div id="title-bar">
                <a href="index.php" class="no-decoration">
                    <img src="assets/bsf-logo-light.png" alt="blog standard food logo" />
                </a>
                <nav>
                    <ul>
                        <li><a href="index.php"><span>THE</span> Archives</a></li>
                        <li><a href="the-lexicon.html"><span>THE</span> Lexicon</a></li>
                        <li><a href="the-soundtrack.html"><span>THE</span> Soundtrack</a></li>
                        <li><a href="#"><span>THE</span> Lowdown</a></li>
                    </ul>
                </nav>
            </div>

            <video autoplay loop poster="vid/bsf-poster.jpg" id="home-page-vid">
                <source src="vid/bsf-slideshow.mp4" type="video/mp4">
                <source src="vid/bsf-slideshow.webm" type="video/webm">
                <source src="vid/bsf-slideshow.ogv" type="video/ogv">
            </video>

            <div id="header-text">
                <h1>Blog Standard Food</h1>
                <p>If we can cook food this good so can you...</p>
            </div>
        </header>


        <div id="grid-articles">
            <?php foreach($this->articles as $article): ?>
            
                <article>
                    <a class="no-decoration" href="articles/<?=$article->getUrl(); ?>">
                        <img 
                            srcset="img/<?php echo $article->getBannerImagePath(); ?>  1000w,
                                    img/thumbs-200w/<?php echo $article->getBannerImagePath(); ?> 200w"
                            src="img/<?php echo $article->getBannerImagePath(); ?>"
                            alt="<?php echo $article->getTitle(); ?>"
                        />
                        <div class="article-info">
                            <h3><?=$article->getTitle(); ?></h3>
                            <p><?=$article->getSummary(); ?></p>
                            <small><i class="fa fa-clock-o"></i> <?=$article->getNicePubDate(); ?></small>
                        </div>
                    </a>
                </article>
            
            <?php endforeach; ?>
        </div>


        <footer>
            <div id="chef-hat"></div>
            <p>Blog Standard Food is <a href="http://www.pjfreeman.co.uk/">Phil Freeman</a> &amp; 
                <a href="http://poc275.co.uk">Peter O'Connor</a>
            </p>
            <address id="footer-social">
                <ul id="footer-logos">
                    <li><a href="mailto:poc275@gmail.com?Subject=A%20Food%20Odyssey" title="send us an email" class="no-decoration"><i class="fa fa-envelope-o fa-4x"></i></a></li>
                    <li><a href="rss.xml" title="follow our blog" class="no-decoration"><i class="fa fa-rss fa-4x"></i></a></li>
                </ul>
            </address>

            <small>
                <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">
                <img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" />
                </a>
                <br />
                <span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Blog Standard Food</span> is licensed under a 
                <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a> 2016.
            </small>

        </footer>

        <script type="text/javascript" src="js/Scroller.js"></script>
    </body>

</html>