<div id="asset-panel">
	<p>Click on an image to insert the Markdown text</p>
	<ul id="assets">
		<?php foreach($this->images as $image): ?>
			<li class="image">
				<div class="asset">
					<div class="asset-img">
						<img class="thumb" src='img/<?=$image; ?>' alt='<?=$image; ?>' title='<?=$image; ?>' />
						<span><?=$image; ?></span>
					</div>
				</div>
			</li>
		<?php endforeach; ?>
	</ul>
</div>

<script>
	var panel = document.getElementById("assets-panel");
	var images = document.getElementById("asset-panel");
	panel.appendChild(images);
</script>